/*
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea;

import com.intellij.openapi.extensions.ExtensionFactory;
import mt.edu.um.cs.rv.idea.lang.ValourLanguage;

public class ValourExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return ValourLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
