/**
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea.highlighting;

import mt.edu.um.cs.rv.idea.highlighting.ValourBaseColorSettingsPage;

@SuppressWarnings("all")
public class ValourColorSettingsPage extends ValourBaseColorSettingsPage {
}
