/*
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea.lang.psi;

import com.intellij.psi.impl.PsiTreeChangeEventImpl;
import com.intellij.psi.util.PsiModificationTracker;
import mt.edu.um.cs.rv.idea.lang.ValourLanguage;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;

public class ValourCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public ValourCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(ValourLanguage.INSTANCE, psiModificationTracker);
	}
	protected boolean hasJavaStructuralChanges(PsiTreeChangeEventImpl event) {
		return true;
	}

}
