/*
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.tests

import com.google.inject.Inject
import mt.edu.um.cs.rv.valour.Model
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(ValourInjectorProvider)
class ValourParsingTest{

	@Inject
	ParseHelper<Model> parseHelper;

	@Test 
	def void loadEmptyModel() {
		val model = parseHelper.parse('''
		''')
		
		Assert.assertNotNull(model)
		Assert.assertNull(model.imports)
	}

	@Test 
	def void loadModelWithImportsOnly() {
		val model = parseHelper.parse('''
			import java.lang.String
			import java.util.UUID
		''')
		
		Assert.assertNotNull(model)
		Assert.assertEquals(2, model.imports.importDeclarations.length)		
	}
	

}
