/**
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.validation;

import mt.edu.um.cs.rv.validation.AbstractValourValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ValourValidator extends AbstractValourValidator {
}
