/**
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea;

import mt.edu.um.cs.rv.idea.AbstractValourIdeaModule;

/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
@SuppressWarnings("all")
public class ValourIdeaModule extends AbstractValourIdeaModule {
}
