/*
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class ValourLanguage extends AbstractXtextLanguage {

	public static final ValourLanguage INSTANCE = new ValourLanguage();

	private ValourLanguage() {
		super("mt.edu.um.cs.rv.Valour");
	}

}
