/*
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ValourStandaloneSetup extends ValourStandaloneSetupGenerated {

	def static void doSetup() {
		new ValourStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
