/*
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class ValourUiModule extends AbstractValourUiModule {
}
