/**
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea.lang;

import mt.edu.um.cs.rv.idea.lang.AbstractValourFileType;

@SuppressWarnings("all")
public class ValourFileType extends AbstractValourFileType {
  public final static ValourFileType INSTANCE = new ValourFileType();
  
  public ValourFileType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(ValourLanguage) is undefined");
  }
}
