/*
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea.lang.pom;

import mt.edu.um.cs.rv.idea.lang.ValourLanguage;
import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;

public class ValourPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public ValourPomDeclarationSearcher() {
		super(ValourLanguage.INSTANCE);
	}
}
