/*
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea.completion

import mt.edu.um.cs.rv.idea.lang.ValourLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class ValourCompletionContributor extends AbstractValourCompletionContributor {
	new() {
		this(ValourLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
