/*
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class ValourIdeaModule extends AbstractValourIdeaModule {
}
