/*
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import mt.edu.um.cs.rv.idea.lang.ValourLanguage;
import org.eclipse.xtext.idea.facet.AbstractFacetType;

public class ValourFacetType extends AbstractFacetType<ValourFacetConfiguration> {

	public static final FacetTypeId<Facet<ValourFacetConfiguration>> TYPEID = new FacetTypeId<Facet<ValourFacetConfiguration>>("mt.edu.um.cs.rv.Valour");

	public ValourFacetType() {
		super(TYPEID, "mt.edu.um.cs.rv.Valour", "Valour");
		ValourLanguage.INSTANCE.injectMembers(this);
	}
}
