/*
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class ValourScopeProvider extends AbstractValourScopeProvider {

}
