/**
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea.completion;

import mt.edu.um.cs.rv.idea.completion.AbstractValourCompletionContributor;
import mt.edu.um.cs.rv.idea.lang.ValourLanguage;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

@SuppressWarnings("all")
public class ValourCompletionContributor extends AbstractValourCompletionContributor {
  public ValourCompletionContributor() {
    this(ValourLanguage.INSTANCE);
  }
  
  public ValourCompletionContributor(final AbstractXtextLanguage lang) {
    super(lang);
  }
}
