/**
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea.completion;

import mt.edu.um.cs.rv.idea.completion.AbstractValourCompletionContributor;

@SuppressWarnings("all")
public class ValourCompletionContributor extends AbstractValourCompletionContributor {
  public ValourCompletionContributor() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe constructor ValourCompletionContributor(AbstractXtextLanguage) refers to the missing type AbstractXtextLanguage");
  }
  
  public ValourCompletionContributor(final /* AbstractXtextLanguage */Object lang) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AbstractXtextLanguage) is undefined");
  }
}
