/**
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.Provider;
import com.google.inject.util.Modules;
import java.util.concurrent.ExecutorService;
import mt.edu.um.cs.rv.ValourRuntimeModule;
import mt.edu.um.cs.rv.ValourStandaloneSetup;
import mt.edu.um.cs.rv.web.ValourWebModule;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ValourWebSetup extends ValourStandaloneSetup {
  private final Provider<ExecutorService> executorServiceProvider;
  
  @Override
  public Injector createInjector() {
    final ValourRuntimeModule runtimeModule = new ValourRuntimeModule();
    final ValourWebModule webModule = new ValourWebModule(this.executorServiceProvider);
    Modules.OverriddenModuleBuilder _override = Modules.override(runtimeModule);
    Module _with = _override.with(webModule);
    return Guice.createInjector(_with);
  }
  
  public ValourWebSetup(final Provider<ExecutorService> executorServiceProvider) {
    super();
    this.executorServiceProvider = executorServiceProvider;
  }
}
