/**
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.web;

import com.google.inject.Provider;
import java.util.concurrent.ExecutorService;
import mt.edu.um.cs.rv.web.AbstractValourWebModule;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ValourWebModule extends AbstractValourWebModule {
  public ValourWebModule(final Provider<ExecutorService> executorServiceProvider) {
    super(executorServiceProvider);
  }
}
