/*
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea.lang


class ValourFileType extends AbstractValourFileType {
	public static final ValourFileType INSTANCE = new ValourFileType()
	
	new() {
		super(ValourLanguage.INSTANCE)
	}
}
