/*
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea.completion;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;
import org.eclipse.xtext.xbase.idea.completion.XbaseCompletionContributor;

public class AbstractValourCompletionContributor extends XbaseCompletionContributor {
	public AbstractValourCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
