/*
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea.highlighting;

import mt.edu.um.cs.rv.idea.lang.ValourLanguage;
import org.eclipse.xtext.idea.highlighting.AbstractColorSettingsPage;

public class ValourBaseColorSettingsPage extends AbstractColorSettingsPage {
	
	public ValourBaseColorSettingsPage() {
		ValourLanguage.INSTANCE.injectMembers(this);
	}

	@Override
	public String getDisplayName() {
		return ValourLanguage.INSTANCE.getDisplayName();
	}
}
