/*
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea.highlighting;

import mt.edu.um.cs.rv.idea.lang.ValourLanguage;
import org.eclipse.xtext.idea.highlighting.SemanticHighlightVisitor;

public class ValourSemanticHighlightVisitor extends SemanticHighlightVisitor {
	public ValourSemanticHighlightVisitor() {
		ValourLanguage.INSTANCE.injectMembers(this);
	}
}
