/*
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea.highlighting;

import com.intellij.openapi.fileTypes.SingleLazyInstanceSyntaxHighlighterFactory;
import com.intellij.openapi.fileTypes.SyntaxHighlighter;
import mt.edu.um.cs.rv.idea.lang.ValourLanguage;
import org.jetbrains.annotations.NotNull;

public class ValourSyntaxHighlighterFactory extends SingleLazyInstanceSyntaxHighlighterFactory {
	
	@Override
    @NotNull
    protected SyntaxHighlighter createHighlighter() {
        return ValourLanguage.INSTANCE.getInstance(SyntaxHighlighter.class);
    }
}
