/**
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv;

import mt.edu.um.cs.rv.AbstractValourRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ValourRuntimeModule extends AbstractValourRuntimeModule {
}
