/**
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv;

import mt.edu.um.cs.rv.ValourStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ValourStandaloneSetup extends ValourStandaloneSetupGenerated {
  public static void doSetup() {
    ValourStandaloneSetup _valourStandaloneSetup = new ValourStandaloneSetup();
    _valourStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
