/*
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea.lang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ValourAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("mt/edu/um/cs/rv/idea/parser/antlr/internal/PsiInternalValour.tokens");
	}
}
