/**
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea.facet;

/* @State(, ) */@SuppressWarnings("all")
public class ValourFacetConfiguration /* implements XbaseFacetConfiguration, PersistentStateComponent<XbaseGeneratorConfigurationState>  */{
}
