/**
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea;

@SuppressWarnings("all")
public class ValourStandaloneSetupIdea /* implements ValourStandaloneSetupGenerated  */{
  @Override
  public Object createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nValourRuntimeModule cannot be resolved."
      + "\nThe method or field Modules2 is undefined"
      + "\nThe method or field Guice is undefined"
      + "\nmixin cannot be resolved"
      + "\ncreateInjector cannot be resolved");
  }
}
