/**
 * generated by Xtext 2.9.2
 */
package mt.edu.um.cs.rv.idea;

@SuppressWarnings("all")
public class ValourIdeaSetup /* implements ISetup  */{
  @Override
  public Object createInjectorAndDoEMFRegistration() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field EcoreGlobalRegistries is undefined"
      + "\nThe method createInjector() from the type ValourStandaloneSetupIdea refers to the missing type Object"
      + "\nensureInitialized cannot be resolved");
  }
}
